# Generated by Django 3.1 on 2020-08-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='url_img',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='camera',
            name='url_vid',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='camera',
            name='ws_img',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='camera',
            name='ws_vid',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
