# Generated by Django 3.1 on 2020-08-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0005_trainframe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainframe',
            old_name='to_go',
            new_name='tfmodel',
        ),
        migrations.RemoveField(
            model_name='trainframe',
            name='weight',
        ),
    ]
