# Generated by Django 3.1 on 2020-08-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0006_auto_20200825_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(max_length=100)),
                ('index', models.SmallIntegerField()),
                ('value', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=256)),
            ],
        ),
    ]
