# Generated by Django 3.1 on 2020-09-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0007_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='epoch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit', models.BigIntegerField()),
                ('loss', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('cmetrics', models.FloatField()),
                ('val_loss', models.FloatField()),
                ('val_accuracy', models.FloatField()),
                ('val_cmetrics', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='fit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made', models.DateTimeField()),
                ('minutes', models.FloatField()),
                ('model', models.IntegerField()),
                ('epochs', models.IntegerField()),
                ('nr_tr', models.IntegerField()),
                ('nr_va', models.IntegerField()),
                ('loss', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('cmetrics', models.FloatField()),
                ('val_loss', models.FloatField()),
                ('val_accuracy', models.FloatField()),
                ('val_cmetrics', models.FloatField()),
                ('cputemp', models.FloatField()),
                ('cpufan1', models.FloatField()),
                ('cpufan2', models.FloatField()),
                ('gputemp', models.FloatField()),
                ('gpufan', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
