# Generated by Django 3.1 on 2020-09-07 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0008_epoch_fit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epoch',
            name='fit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_client.fit'),
        ),
    ]
