# Generated by Django 3.1 on 2020-09-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0009_auto_20200907_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfmodel',
            name='lastclean',
            field=models.DateTimeField(),
        ),
    ]
