# Generated by Django 3.1 on 2020-09-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0010_auto_20200909_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tfmodel',
            name='lastclean',
        ),
    ]
