# Generated by Django 3.1 on 2020-09-09 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0011_remove_tfmodel_lastclean'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfmodel',
            name='lastclean',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 13, 3, 20, 325629)),
        ),
        migrations.AlterField(
            model_name='tfmodel',
            name='lastfile',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 13, 3, 20, 325613)),
        ),
    ]
