# Generated by Django 3.1 on 2020-09-09 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0012_auto_20200909_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tfmodel',
            name='lastclean',
        ),
        migrations.AlterField(
            model_name='tfmodel',
            name='lastfile',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 13, 4, 22, 962291)),
        ),
    ]
