# Generated by Django 3.1 on 2020-09-12 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0022_auto_20200912_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.SmallIntegerField(default=0)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('end2', models.DateTimeField()),
                ('xmin', models.IntegerField()),
                ('xmax', models.IntegerField()),
                ('ymin', models.IntegerField()),
                ('ymax', models.IntegerField()),
                ('numframes', models.IntegerField()),
                ('xminmarg', models.IntegerField()),
                ('xmaxmarg', models.IntegerField()),
                ('yminmarg', models.IntegerField()),
                ('ymaxmarg', models.IntegerField()),
                ('tfmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_client.tfmodel')),
            ],
        ),
    ]
