# Generated by Django 3.1 on 2020-09-12 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0023_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='checked',
            new_name='status',
        ),
        migrations.CreateModel(
            name='event_frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('status', models.SmallIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('x1', models.IntegerField()),
                ('x2', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('y2', models.IntegerField()),
                ('x1marg', models.IntegerField()),
                ('x2marg', models.IntegerField()),
                ('y1marg', models.IntegerField()),
                ('y2marg', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_client.event')),
            ],
        ),
    ]
