# Generated by Django 3.1 on 2020-09-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0024_auto_20200912_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_frame',
            name='train',
            field=models.IntegerField(default=0),
        ),
    ]
