# Generated by Django 3.1 on 2020-09-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0025_event_frame_train'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_frame',
            name='train',
        ),
    ]
