# Generated by Django 3.1 on 2020-09-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0026_remove_event_frame_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_frame',
            name='trainframe',
            field=models.BigIntegerField(default=0),
        ),
    ]
