# Generated by Django 3.1 on 2020-09-21 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0027_event_frame_trainframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_frame',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='c_client.event'),
        ),
    ]
