# Generated by Django 3.1 on 2020-09-21 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0028_auto_20200921_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_frame',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_client.event'),
        ),
    ]
