# Generated by Django 3.1 on 2020-09-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0029_auto_20200921_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='cam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eins', models.IntegerField(default=1)),
                ('zwei', models.IntegerField(default=2)),
                ('drei', models.IntegerField(default=3)),
            ],
        ),
    ]
