# Generated by Django 3.1 on 2020-09-23 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0030_cam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cam',
            name='drei',
        ),
        migrations.RemoveField(
            model_name='cam',
            name='eins',
        ),
        migrations.RemoveField(
            model_name='cam',
            name='zwei',
        ),
        migrations.AddField(
            model_name='cam',
            name='fps',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cam',
            name='lastused',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='cam',
            name='made',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='cam',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cam',
            name='url_img',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='cam',
            name='url_vid',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='cam',
            name='xres',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cam',
            name='yres',
            field=models.IntegerField(default=0),
        ),
    ]
