# Generated by Django 3.1 on 2020-09-23 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0032_auto_20200923_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cam',
            name='active',
        ),
        migrations.RemoveField(
            model_name='cam',
            name='running',
        ),
    ]
