# Generated by Django 3.1 on 2020-09-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0034_auto_20200923_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cam',
            old_name='fps',
            new_name='fpsactual',
        ),
        migrations.AddField(
            model_name='cam',
            name='fpslimit',
            field=models.FloatField(default=0),
        ),
    ]
