# Generated by Django 3.1 on 2020-09-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0035_auto_20200923_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='cam',
            name='feed_type',
            field=models.IntegerField(default=1),
        ),
    ]
