# Generated by Django 3.1 on 2020-09-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0037_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='cam',
            name='ibn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cam',
            name='ibt',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='cam',
            name='obn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cam',
            name='obt',
            field=models.CharField(default='', max_length=2),
        ),
    ]
