# Generated by Django 3.1 on 2020-09-30 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0039_auto_20200930_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cam',
            name='ibn',
        ),
        migrations.RemoveField(
            model_name='cam',
            name='ibt',
        ),
        migrations.RemoveField(
            model_name='cam',
            name='obn',
        ),
        migrations.RemoveField(
            model_name='cam',
            name='obt',
        ),
        migrations.RemoveField(
            model_name='view',
            name='ibn',
        ),
        migrations.RemoveField(
            model_name='view',
            name='ibt',
        ),
        migrations.RemoveField(
            model_name='view',
            name='obn',
        ),
        migrations.RemoveField(
            model_name='view',
            name='obt',
        ),
    ]
