# Generated by Django 3.1 on 2020-09-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0042_remove_cam_view_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='cam',
            name='view_out',
            field=models.ManyToManyField(to='c_client.view'),
        ),
    ]
