# Generated by Django 3.1 on 2020-09-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0045_auto_20200930_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cam',
            name='view_out',
        ),
        migrations.RemoveField(
            model_name='view',
            name='view_out',
        ),
    ]
