# Generated by Django 3.1 on 2020-09-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0046_auto_20200930_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='cam',
            name='obuffers',
            field=models.CharField(default='[]', max_length=255),
        ),
        migrations.AddField(
            model_name='view',
            name='obuffers',
            field=models.CharField(default='[]', max_length=255),
        ),
    ]
