# Generated by Django 3.1 on 2020-09-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0047_auto_20200930_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cam',
            old_name='obuffers',
            new_name='outbuffers',
        ),
        migrations.RenameField(
            model_name='view',
            old_name='obuffers',
            new_name='outbuffers',
        ),
    ]
