# Generated by Django 3.1 on 2020-09-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0048_auto_20200930_1538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='camera',
        ),
    ]
