# Generated by Django 3.1 on 2020-10-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0049_delete_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='source_nr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='view',
            name='source_type',
            field=models.CharField(default='X', max_length=1),
        ),
    ]
