# Generated by Django 3.1 on 2020-10-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0052_auto_20201002_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='source_type',
            field=models.CharField(default='X', max_length=1),
        ),
    ]
