# Generated by Django 3.1 on 2020-10-02 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0053_view_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='detctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('made', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('lastused', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('xres', models.IntegerField(default=0)),
                ('yres', models.IntegerField(default=0)),
                ('fpslimit', models.FloatField(default=0)),
                ('fpsactual', models.FloatField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('outbuffers', models.CharField(default='[]', max_length=255)),
                ('backgr_delay', models.IntegerField(default=3)),
                ('dilation', models.IntegerField(default=50)),
                ('erosion', models.IntegerField(default=2)),
                ('max_size', models.IntegerField(default=100)),
                ('threshold', models.IntegerField(default=70)),
                ('max_rect', models.IntegerField(default=10)),
                ('mask', models.CharField(default='***Dummy***', max_length=20)),
            ],
        ),
    ]
