# Generated by Django 3.1 on 2020-10-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0054_detctor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='detctor',
            new_name='detector',
        ),
    ]
