# Generated by Django 3.1 on 2020-10-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0056_eventer'),
    ]

    operations = [
        migrations.AddField(
            model_name='detector',
            name='eventer',
            field=models.IntegerField(default=1),
        ),
    ]
