# Generated by Django 3.1 on 2020-10-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0057_detector_eventer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventer',
            name='event_time_gap',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='eventer',
            name='margin',
            field=models.IntegerField(default=50),
        ),
    ]
