# Generated by Django 3.1 on 2020-10-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0058_auto_20201009_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.RemoveField(
            model_name='event',
            name='xmaxmarg',
        ),
        migrations.RemoveField(
            model_name='event',
            name='xminmarg',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ymaxmarg',
        ),
        migrations.RemoveField(
            model_name='event',
            name='yminmarg',
        ),
    ]
