# Generated by Django 3.1 on 2020-10-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0059_auto_20201009_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='cam',
            name='school',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detector',
            name='school',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eventer',
            name='school',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='view',
            name='school',
            field=models.IntegerField(default=1),
        ),
    ]
