# Generated by Django 3.1 on 2020-10-10 08:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0060_auto_20201010_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='lastused',
            field=models.DateTimeField(default=datetime.datetime(1899, 12, 31, 23, 7, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cam',
            name='made',
            field=models.DateTimeField(default=datetime.datetime(1899, 12, 31, 23, 7, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='detector',
            name='lastused',
            field=models.DateTimeField(default=datetime.datetime(1899, 12, 31, 23, 7, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='detector',
            name='made',
            field=models.DateTimeField(default=datetime.datetime(1899, 12, 31, 23, 7, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventer',
            name='lastused',
            field=models.DateTimeField(default=datetime.datetime(1899, 12, 31, 23, 7, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventer',
            name='made',
            field=models.DateTimeField(default=datetime.datetime(1899, 12, 31, 23, 7, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tfmodel',
            name='lastclean',
            field=models.DateTimeField(default=datetime.datetime(1899, 12, 31, 23, 7, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tfmodel',
            name='lastfile',
            field=models.DateTimeField(default=datetime.datetime(1899, 12, 31, 23, 7, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='view',
            name='lastused',
            field=models.DateTimeField(default=datetime.datetime(1899, 12, 31, 23, 7, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='view',
            name='made',
            field=models.DateTimeField(default=datetime.datetime(1899, 12, 31, 23, 7, tzinfo=utc)),
        ),
    ]
