# Generated by Django 3.1 on 2020-10-10 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0061_auto_20201010_1046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tfmodel',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='tfmodel',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='trainframe',
            old_name='tfmodel',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='tfmodel',
            new_name='school',
        ),
        migrations.RemoveField(
            model_name='event',
            name='closed',
        ),
    ]
