# Generated by Django 3.1 on 2020-10-10 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0063_auto_20201010_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_frame',
            name='x1marg',
        ),
        migrations.RemoveField(
            model_name='event_frame',
            name='x2marg',
        ),
        migrations.RemoveField(
            model_name='event_frame',
            name='y1marg',
        ),
        migrations.RemoveField(
            model_name='event_frame',
            name='y2marg',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='school',
        ),
    ]
