# Generated by Django 3.1 on 2020-10-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0066_auto_20201022_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epoch',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='val_accuracy',
        ),
    ]
