# Generated by Django 3.1 on 2020-10-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0067_auto_20201022_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epoch',
            name='val_accuracy',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='accuracy',
        ),
    ]
