# Generated by Django 3.1 on 2020-10-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0068_auto_20201022_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='xdim',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='ydim',
            field=models.IntegerField(default=0),
        ),
    ]
