# Generated by Django 3.1 on 2020-10-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0070_view_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cam',
            name='fps_div',
            field=models.FloatField(default=0),
        ),
    ]
