# Generated by Django 3.1 on 2020-11-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0071_cam_fps_div'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='feed_type',
            field=models.IntegerField(choices=[(1, 'JPeg'), (2, 'Others'), (3, 'RTSP')], default=1, verbose_name='feed type'),
        ),
        migrations.AlterField(
            model_name='cam',
            name='fps_div',
            field=models.FloatField(default=0, verbose_name='FPS divisor'),
        ),
        migrations.AlterField(
            model_name='cam',
            name='fpslimit',
            field=models.FloatField(default=0, verbose_name='FPS limit'),
        ),
        migrations.AlterField(
            model_name='cam',
            name='url_img',
            field=models.CharField(default='', max_length=256, verbose_name='image url'),
        ),
        migrations.AlterField(
            model_name='cam',
            name='url_vid',
            field=models.CharField(default='', max_length=256, verbose_name='video url'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='backgr_delay',
            field=models.IntegerField(default=3, verbose_name='background delay'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='dilation',
            field=models.IntegerField(default=50, verbose_name='dilation'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='erosion',
            field=models.IntegerField(default=2, verbose_name='erosion'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='max_rect',
            field=models.IntegerField(default=10, verbose_name='max. number'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='max_size',
            field=models.IntegerField(default=100, verbose_name='max. size'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='threshold',
            field=models.IntegerField(default=70, verbose_name='threshold'),
        ),
        migrations.AlterField(
            model_name='eventer',
            name='event_time_gap',
            field=models.IntegerField(default=60, verbose_name='new event gap'),
        ),
        migrations.AlterField(
            model_name='eventer',
            name='margin',
            field=models.IntegerField(default=50, verbose_name='frame margin'),
        ),
    ]
