# Generated by Django 3.1 on 2020-11-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0072_auto_20201116_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='mask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('definition', models.CharField(default='[]', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='detector',
            name='mask',
        ),
    ]
