# Generated by Django 3.1 on 2020-11-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0074_mask_cam'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='apply_mask',
            field=models.BooleanField(default=False),
        ),
    ]
