# Generated by Django 3.1 on 2020-11-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0075_view_apply_mask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='apply_mask',
        ),
        migrations.AddField(
            model_name='cam',
            name='apply_mask',
            field=models.BooleanField(default=False),
        ),
    ]
