# Generated by Django 3.1 on 2020-12-03 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0077_auto_20201202_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventer',
            name='school',
            field=models.IntegerField(default=1, verbose_name='school'),
        ),
        migrations.CreateModel(
            name='evt_condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('and_or', models.IntegerField(choices=[(0, 'and'), (1, 'or')], default=0, verbose_name='and_or')),
                ('c_type', models.IntegerField(choices=[(0, 'x values above or equal y'), (1, 'x values below or equal y'), (2, 'tag x is in top y'), (3, 'tag x is above or equal y'), (4, 'tag x is below or equal y')], default=0, verbose_name='c_type')),
                ('x', models.IntegerField(default=1, verbose_name='x')),
                ('y', models.FloatField(default=0.5, verbose_name='y')),
                ('eventer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_client.eventer')),
            ],
        ),
    ]
