# Generated by Django 3.1 on 2020-12-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0078_auto_20201203_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='evt_condition',
            name='reaction',
            field=models.IntegerField(choices=[(0, 'show frame'), (1, 'send school'), (2, 'record video'), (3, 'send email'), (4, 'alarm')], default=0, verbose_name='reaction'),
        ),
    ]
