# Generated by Django 3.1 on 2020-12-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0079_evt_condition_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='epoch',
            name='fbeta2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='epoch',
            name='val_fbeta2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fit',
            name='fbeta2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fit',
            name='val_fbeta2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='evt_condition',
            name='c_type',
            field=models.IntegerField(choices=[(1, 'any movement detection'), (2, 'x values above or equal y'), (3, 'x values below or equal y'), (4, 'tag x is above or equal y'), (5, 'tag x is below or equal y'), (6, 'tag x is in top y')], default=1, verbose_name='c_type'),
        ),
        migrations.AlterField(
            model_name='evt_condition',
            name='reaction',
            field=models.IntegerField(choices=[(1, 'show frame'), (2, 'send school'), (3, 'record video'), (4, 'send email'), (5, 'alarm')], default=0, verbose_name='reaction'),
        ),
    ]
