# Generated by Django 3.1 on 2020-12-25 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0080_auto_20201225_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epoch',
            name='fbeta2',
        ),
        migrations.RemoveField(
            model_name='epoch',
            name='val_fbeta2',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='fbeta2',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='val_fbeta2',
        ),
    ]
