# Generated by Django 3.1 on 2020-12-29 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('c_client', '0081_auto_20201225_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='locktime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='userlock',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
