# Generated by Django 3.1 on 2020-12-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0082_auto_20201229_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='access_control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtype', models.CharField(max_length=1)),
                ('vid', models.IntegerField()),
                ('u_g', models.CharField(default='U', max_length=1)),
                ('u_g_nr', models.IntegerField(default=0)),
                ('r_w', models.CharField(default='R', max_length=1)),
            ],
        ),
    ]
