# Generated by Django 3.1 on 2021-01-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0084_trainframe_made_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end2',
        ),
    ]
