# Generated by Django 3.1 on 2021-01-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0085_remove_event_end2'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='last_id_mf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='last_id_of',
            field=models.IntegerField(default=0),
        ),
    ]
