# Generated by Django 3.1 on 2021-01-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0088_auto_20210119_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoclip',
            name='num_views',
            field=models.IntegerField(default=0),
        ),
    ]
