# Generated by Django 3.1 on 2021-01-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0089_videoclip_num_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='videoclips',
        ),
        migrations.AddField(
            model_name='event',
            name='videoclips',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.DeleteModel(
            name='videoclip',
        ),
    ]
