# Generated by Django 3.1 on 2021-01-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0091_auto_20210123_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='double',
            field=models.BooleanField(default=False),
        ),
    ]
