# Generated by Django 3.1 on 2021-01-30 12:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0093_eventer_alarm_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(1899, 12, 31, 23, 7, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='numframes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='c_client.school'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(1899, 12, 31, 23, 7, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='xmax',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='xmin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='ymax',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='ymin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event_frame',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='c_client.event'),
        ),
        migrations.AlterField(
            model_name='event_frame',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(1899, 12, 31, 23, 7, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event_frame',
            name='x1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event_frame',
            name='x2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event_frame',
            name='y1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event_frame',
            name='y2',
            field=models.IntegerField(default=0),
        ),
    ]
