# Generated by Django 3.1 on 2021-02-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0094_auto_20210130_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='p_string',
            field=models.CharField(default='[]', max_length=255),
        ),
    ]
