# Generated by Django 3.1 on 2021-02-10 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0095_event_p_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cam',
            name='fps_div',
        ),
    ]
