# Generated by Django 3.1 on 2021-03-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0096_remove_cam_fps_div'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='active',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='sorting',
        ),
    ]
