# Generated by Django 3.1 on 2021-03-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0097_auto_20210311_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='do_filter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='load_model_nr',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='school',
            name='train_on_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='used_by_others',
            field=models.BooleanField(default=True),
        ),
    ]
