# Generated by Django 3.1 on 2021-03-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0098_auto_20210311_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='xdim',
        ),
        migrations.RemoveField(
            model_name='school',
            name='ydim',
        ),
        migrations.AlterField(
            model_name='school',
            name='used_by_others',
            field=models.BooleanField(default=False),
        ),
    ]
