# Generated by Django 3.1 on 2021-03-11 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0099_auto_20210311_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='lastclean',
        ),
    ]
