# Generated by Django 3.1 on 2021-03-11 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0100_remove_school_lastclean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='type',
        ),
    ]
