# Generated by Django 3.1 on 2021-03-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0101_remove_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='school',
            field=models.SmallIntegerField(default=0),
        ),
    ]
