# Generated by Django 3.1 on 2021-03-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0102_tag_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='replaces',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
