# Generated by Django 3.1 on 2021-03-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0103_tag_replaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='repeater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
