# Generated by Django 3.1 on 2021-03-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0104_repeater'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeater',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
