# Generated by Django 3.1 on 2021-03-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0105_repeater_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='l_rate_max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='school',
            name='l_rate_min',
            field=models.FloatField(default=0.0),
        ),
    ]
