# Generated by Django 3.1 on 2021-03-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0106_auto_20210319_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='cam',
            name='repeater',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repeater',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='l_rate_max',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AlterField(
            model_name='school',
            name='l_rate_min',
            field=models.FloatField(default=-1.0),
        ),
    ]
