# Generated by Django 3.1 on 2021-03-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0107_auto_20210319_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='l_rate_max',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='l_rate_min',
            field=models.CharField(default='-1', max_length=20),
        ),
    ]
