# Generated by Django 3.1 on 2021-06-24 18:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0110_school_e_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('made', models.DateTimeField(default=datetime.datetime(1899, 12, 31, 23, 7, tzinfo=utc))),
                ('lastused', models.DateTimeField(default=datetime.datetime(1899, 12, 31, 23, 7, tzinfo=utc))),
                ('cam_xres', models.IntegerField(default=0)),
                ('cam_yres', models.IntegerField(default=0)),
                ('cam_fpslimit', models.FloatField(default=0, verbose_name='FPS limit')),
                ('cam_fpsactual', models.FloatField(default=0)),
                ('cam_active', models.BooleanField(default=True)),
                ('cam_feed_type', models.IntegerField(choices=[(1, 'JPeg'), (2, 'Others'), (3, 'RTSP')], default=1, verbose_name='feed type')),
                ('cam_url', models.CharField(default='', max_length=256, verbose_name='url')),
                ('cam_apply_mask', models.BooleanField(default=False)),
                ('cam_repeater', models.IntegerField(default=0)),
            ],
        ),
    ]
