# Generated by Django 3.1 on 2021-06-24 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0112_auto_20210624_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventer',
            name='made',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
