# Generated by Django 3.1 on 2021-06-24 18:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0114_auto_20210624_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventer',
            name='made',
            field=models.DateTimeField(default=datetime.datetime(1899, 12, 31, 23, 7, tzinfo=utc)),
        ),
    ]
