# Generated by Django 3.1 on 2021-06-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0115_auto_20210624_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='lastused',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='stream',
            name='made',
            field=models.DateTimeField(default=0),
        ),
    ]
