# Generated by Django 3.1 on 2021-06-24 18:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0116_auto_20210624_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='lastused',
            field=models.DateTimeField(default=datetime.datetime(1899, 12, 31, 23, 7, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='stream',
            name='made',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 18, 45, 5, 17909, tzinfo=utc)),
        ),
    ]
