# Generated by Django 3.1 on 2021-06-24 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0117_auto_20210624_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='lastused',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stream',
            name='made',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
