# Generated by Django 3.1 on 2021-06-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0118_auto_20210624_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='det_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='det_backgr_delay',
            field=models.IntegerField(default=3, verbose_name='background delay'),
        ),
        migrations.AddField(
            model_name='stream',
            name='det_dilation',
            field=models.IntegerField(default=50, verbose_name='dilation'),
        ),
        migrations.AddField(
            model_name='stream',
            name='det_erosion',
            field=models.IntegerField(default=2, verbose_name='erosion'),
        ),
        migrations.AddField(
            model_name='stream',
            name='det_fpsactual',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='det_max_rect',
            field=models.IntegerField(default=10, verbose_name='max. number'),
        ),
        migrations.AddField(
            model_name='stream',
            name='det_max_size',
            field=models.IntegerField(default=100, verbose_name='max. size'),
        ),
        migrations.AddField(
            model_name='stream',
            name='det_threshold',
            field=models.IntegerField(default=70, verbose_name='threshold'),
        ),
    ]
