# Generated by Django 3.1 on 2021-06-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0119_auto_20210624_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='evt_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='evt_alarm_email',
            field=models.CharField(default='', max_length=255, verbose_name='alarm email'),
        ),
        migrations.AddField(
            model_name='stream',
            name='evt_event_time_gap',
            field=models.IntegerField(default=60, verbose_name='new event gap'),
        ),
        migrations.AddField(
            model_name='stream',
            name='evt_fpsactual',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='evt_margin',
            field=models.IntegerField(default=50, verbose_name='frame margin'),
        ),
        migrations.AddField(
            model_name='stream',
            name='evt_school',
            field=models.IntegerField(default=1, verbose_name='school'),
        ),
    ]
