# Generated by Django 3.1 on 2021-12-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_client', '0120_auto_20210624_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='model_type',
            field=models.CharField(default='cam-ai_model', max_length=50),
        ),
    ]
